# Unit 3 Sections 14 and 15
> Libraries and Random Values
 
- toc: true
- branch: master
- badges: true
- comments: true
- tags: [chapter3, week16]
- categories: [chapter3, week16]

<style>
    .coolCode {
        color: #FFFFFF;
        font-family: monospace;
        border: 1px solid #404040;
        border-radius: 3px;
        background-color: #212121;
        padding: 1px 5px;
        font-size: 20px
    }
</style>

# Libraries

* A library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations. 
* These precompiled codes can be referred to as modules. Each module contains bundles of code that can be used repeatedly in different programs.
* A library may also contain documentation, configuration data, message templates, classes, and values, etc.

### Why are libraries important?
* Using Libraries makes Python Programming simpler and convenient for the programmer. 
* One example would be through looping and iteration, as we don’t need to write the same code again and again for different programs. 
* Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

### A few libraries that simplify coding processes:
* **Pillow** allows you to work with images.
* **Tensor Flow** helps with data automation and monitors performance.
* **Matplotlib** allows you to make 2D graphs and plots.

The AP Exam Refrence Sheet itself is a library!

## Hacks:
Research two other Python Libraries NOT DISCUSSED DURING LESSON and make a markdown post, explaining their function and how it helps programmers code.

### API’s
* An Application Program Interface, or API, contains specific direction for how the procedures in a library behave and can be used. 
* An API acts as a gateway for the imported procedures from a library to interact with the rest of your code.

### Activity: Walkthrough with NumPy
* Install NumPy on VSCode:
    1. Open New Terminal In VSCode:
    2. pip3 install --upgrade pip
    3. pip install numpy 
 
REMEMBER: When running library code cells use Python Interpreter Conda (Version 3.9.12)
 
### Example of using NumPy for arrays:

In [2]:
import numpy as np
new_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
 
print (new_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Example of using NumPy for derivatives:

In [1]:
import numpy as np
 
# defining polynomial function
var = np.poly1d([2, 0, 1])
print("Polynomial function, f(x):\n", var)
 
# calculating the derivative
derivative = var.deriv()
print("Derivative, f(x)'=", derivative)
 
# calculates the derivative of after
# given value of x
print("When x=5  f(x)'=", derivative(5))



Polynomial function, f(x):
    2
2 x + 1
Derivative, f(x)'=  
4 x
When x=5  f(x)'= 20


## Random Values

* Random number generation (RNG) produces a random number (crazy right?)
    - This means that a procedure with RNG can return different values even if the parameters (inputs) do not change
* CollegeBoard uses <code class="coolCode">RANDOM(A, B)</code>, to return an integer between integers <code class="coolCode">A</code> and <code class="coolCode">B</code>.
    - RANDOM(1, 10) can output 1, 2, 3, 4, 5, 6, 7, 8, 9, or 10
    - In Python, this would be <code class="coolCode">random.randint(A, B)</code>, after importing Python's "random" library (<code class="coolCode">import random</code>)
    - JavaScript's works a little differently, with <code class="coolCode">Math.random()</code> returning a value between 0 and 1.
        - To match Python and CollegeBoard, you could make a procedure like [this](https://stackoverflow.com/a/7228322)

#### CollegeBoard Example: What is the possible range of values for *answ3*
![CollegeBoard](https://i.ibb.co/Wt90Hbz/Screen-Shot-2022-12-12-at-7-27-58-AM.png)


#### Convert the following procedure to Python, then determine the range of outputs if n = 5.
<pre>
<font color=white>
PROCEDURE Dice(n)
	sum ← 0
	REPEAT UNTIL n = 0
		sum ← sum + RANDOM(1, 6)
		n ← n - 1
	RETURN sum
</font>
</pre>


In [9]:
import random # Fill in the blank

def Dice(n):
    sum = 0
    while n > 0: 
        sum = sum + random.randint(1,6)
        n -= 1
    return sum
Dice(5) # Will output the sum of the 5 dice rolls 

15

## Homework
1. Write a procedure that generates *n* random numbers, then sorts those numbers into lists of even and odd numbers (JS or Python, Python will be easier).

2. Using NumPy and only coding in python cell, find the answer to the following questions:
    a. What is the derivative of 2x^5 - 6x^2 + 24x?
    b. What is the derivative of (13x^4 + 4x^2) / 2 when x = 9? 

3. Suppose you have a group of 10 dogs and 10 cats, and you want to create a random order for them. Show how random number generation could be used to create this random order.

## Modules 
- requests: Allows you to send HTTP requests to web servers and get responses back. Has built in functions for GET, POST, PUT, DELETE, etc. (the most common HTTP requests). Highly customizable allowing you to set headers, cookies, and other parameters. Which allows the module to be used for a wide variety of tasks such as web scraping, web automation, and API testing.
 
- emoji: Allows you to use emojis in your code. This is useful for when you want to add emojis to your code. Also allows you to convert emojis to text and text to emojis. Along with mutliple functions for working with emojis. An example of this would be the ability to get a list of all emojis or other emoji related antics. 

In [23]:
import random
numbers = []
def numsorter(n):
    print("Number of numbers is " + str(n))
    while n > 0:
        numbers.append(random.randrange(n+1))
        n -= 1
    for number in numbers:
        if number%2 == 0:
            print(str(number) + " is even.")
        else:
            print(str(number) + " is odd.")

num = int(input("Enter the amount of numbers."))
numsorter(num)

Number of numbers is 10
0 is even.
8 is even.
4 is even.
7 is odd.
3 is odd.
1 is odd.
1 is odd.
2 is even.
1 is odd.
1 is odd.


In [1]:
import numpy as np 

function = [2, 0, 0, -6, 24, 0]

def derivitatetaker(polynomial):
    var = np.poly1d(polynomial)
    derivative = var.deriv()
    print(derivative)

derivitatetaker(function)

    4
10 x - 12 x + 24


In [53]:
import numpy as np

function = [6.5, 0, 2, 0, 0]

def derivitatetaker(polynomial,x):
    var = np.poly1d(polynomial)
    derivative = var.deriv()
    print("Your function's derivative is\n" + str(derivative) + " when x = " + str(x) + " so f'(" + str(x) + ") = " + str(derivative(x)))

derivitatetaker(function, 9)


Your function's derivative is
    3
26 x + 4 x when x = 9 so f'(9) = 18990.0


In [69]:
import random

dogscats = ["dog"] * 10 + ["cat"] * 10

def petjuggler(pets):
    random.shuffle(pets)
    for pet in pets:
        print(pet, end=" ")
    
petjuggler(dogscats)

cat cat dog dog dog cat cat dog cat cat dog dog cat dog dog dog cat dog cat cat 